name: mandirifurnitureapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  date_field: ^3.0.5
  http: ^0.13.5
  shared_preferences: ^2.1.0
  quickalert: ^1.0.2
  shimmer: ^2.0.0
  lecle_flutter_carousel_pro: ^0.0.3
  page_transition: ^2.1.0
  easy_stepper: ^0.8.3
  expandable_page_view: ^1.0.17
  dropdown_search: ^0.5.0
  flutter_stripe: ^8.0.0

  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/background/
    - assets/content/
    - assets/content-categories/

fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf